### ISSUE TITLE
Progressbar doc test failing due to static member varible

### ISSUE THREAD

**Issue by joeletho** [JustWhit3/osmanip#18]
Hi @JustWhit3,
 I'm implementing ```OutputRedirector``` tests and they've caused ```ProgressBar``` tests to throw an exception when it attempts to set an already existing style:
```[doctest] doctest version is "2.3.6"
[doctest] run with "--help" for options
===============================================================================
test/unit_tests/progressbar/tests_progress_bar.cpp:39:
TEST CASE:  Testing the ProgressBar class methods.<float>
  Testing addStyle method.

test/unit_tests/progressbar/tests_progress_bar.cpp:39: ERROR: test case THREW exception: exception thrown in subcase - will translate later when the whole test case has been exited (cannot translate while there is an active exception)

===============================================================================
test/unit_tests/progressbar/tests_progress_bar.cpp:39:
TEST CASE:  Testing the ProgressBar class methods.<float>

test/unit_tests/progressbar/tests_progress_bar.cpp:39: ERROR: test case THREW exception: Inserted ProgressBar style "|100" is already available!

===============================================================================
[doctest] test cases:     15 |     13 passed |      2 failed |      0 skipped
[doctest] assertions:   1130 |   1129 passed |      1 failed |
[doctest] Status: FAILURE!
```
I'm guessing that since the ```ProgressBar``` uses a ```static``` style map, ```OutputRedirector``` it adds the style to the before the ```ProgressBar``` performs its own test.

Is there a way to the style map before/after use?

**Comment by JustWhit3** [comment]
Hi @joeletho the relevant part of your output is:

```txt
test/unit_tests/progressbar/tests_progress_bar.cpp:39: ERROR: test case THREW exception: Inserted ProgressBar style "|100" is already available!
```

In particular the exception message says:

```txt
ProgressBar style "|100" is already available!
```

This may be due to the fact that you added the "|100" style two times in the same progressbar, while it has been already added. So basically something like:

```cpp
progressbar.setStyle( "indicator", "|100" ); // OK
progressbar.addStyle( "indicator", "|100" ); // EXCEPTION: the |100 already exists in the map
```

You have to remove the second line, or replace "|100" with another string. Tell me if this can help you solving the problem, so we can close the issue.

PS: I am planning to remove exceptions from this library and replace them with a more comfortable error-handling feature.

**Comment by joeletho** [comment]
Thanks for the quick response. The exception is actually thrown from ```test/unit_tests/progressbar/tests_progress_bar.cpp:39```. However, it's because the ```OutputRedirector``` has already added the "|100" style when ```ProgressBar``` tries to add it again. I've changed up my code to use different indicator and loader symbols when testing a mixed bar, so nothing else needs to be changed.

```[doctest] doctest version is "2.3.6"
[doctest] run with "--help" for options
===============================================================================
[doctest] test cases:     15 |     15 passed |      0 failed |      0 skipped
[doctest] assertions:   1149 |   1149 passed |      0 failed |
[doctest] Status: SUCCESS!
```

Definitely let me know when you start to implement the new error-handling system and I'll follow suit.

Thanks again!

**Comment by JustWhit3** [comment]
Ok, I'll have a look to this issue tomorrow. Maybe I can change this feature and let the possibility to add an existing style without nothing happening in this specific case, so you can continue with tests.

Let tou know very soon.

**Comment by joeletho** [comment]
Another test is failing and it's for unrelated reasons. This happens on the current build:


```
$ ./bin/tests --subcase="Testing time methods."
[doctest] doctest version is "2.3.6"   
[doctest] run with "--help" for options
===============================================================================
test/unit_tests/progressbar/tests_progress_bar.cpp:39:
TEST CASE:  Testing the ProgressBar class methods.<long double>
  Testing time methods.

test/unit_tests/progressbar/tests_progress_bar.cpp:179: ERROR: CHECK( agr::IsInBounds( static_cast <int>( bar.getTime() ), 490, 510 ) ) is NOT correct!
  values: CHECK( false )

===============================================================================
test/unit_tests/progressbar/tests_progress_bar.cpp:39:
TEST CASE:  Testing the ProgressBar class methods.<long int>
  Testing time methods.

test/unit_tests/progressbar/tests_progress_bar.cpp:179: ERROR: CHECK( agr::IsInBounds( static_cast <int>( bar.getTime() ), 490, 510 ) ) is NOT correct!
  values: CHECK( false )

===============================================================================
[doctest] test cases:     15 |     13 passed |      2 failed |      0 skipped
[doctest] assertions:    149 |    147 passed |      2 failed |
[doctest] Status: FAILURE!
```

I have no idea why this is happening; and I don't know if this is something on my end. Should I open another ticket?

**Comment by joeletho** [comment]
Sorry, I did not mean to close the ticket just now.

**Comment by JustWhit3** [comment]
Oh, don't worry about these tests, they are related to the `bar.getTime()` method, which gives slightly different results depending on the machine you are running on. It is not necessary to have a fixed output from that method. That's not a problem, you can ignore them.

I will add a comment about this thing soon, so other people will not worry about these tests failure.

**Comment by joeletho** [comment]
OK good to know! I'm sorry to bring up another one (I meant to include it with the last post), but this happens with the include test in ```all_tests.sh```: 

```In file included from multiple_include.cpp:1:
include_one.hpp:3:10: fatal error: osmanip/graphics/canvas.hpp: No such file or directory
    3 | #include <osmanip/graphics/canvas.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
rm: cannot remove 'a.out': No such file or directory
In file included from multiple_include.cpp:1:
include_one.hpp:3:10: fatal error: osmanip/graphics/plot_2D.hpp: No such file or directory
    3 | #include <osmanip/graphics/plot_2D.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
rm: cannot remove 'a.out': No such file or directory
.
.
.
```
Even with this error, everything runs as expected and we can close this.

Thanks!

**Comment by JustWhit3** [comment]
This error is probably due to the fact that you forgot to install the library into your system. Run the `install.sh` script before and you'll see that also that test will pass.

**Comment by joeletho** [comment]
Nailed it! Thanks for clearing that up.
