### ISSUE TITLE
Improve the building process with CMake

### ISSUE THREAD

**Issue by JustWhit3** [JustWhit3/osmanip#28]
Building process is 100% correctly working, but relies on `GNU make` tool. It would be good to upgrade it with a more modern tool like `CMake`.

**Comment by JustWhit3** [comment]
Hi @joeletho ,

This seems a good task for you, since if I correctly remember you told me that were trying to compile the library with `CMake` in your personal environment. If you want to implement your build system improvements also in the main branch and update it with respect to the current build process it would be a good idea. Tell me if you have time to do it.

Cheers.

**Comment by joeletho** [comment]
Hi @JustWhit3,

It's funny that you mention this because I was actually considering doing this very thing next. I actually had to use ```CMake``` again for the most recent work I did for ```OutputRedirector``` in order to enable a proper debug environment. So I think incorporating ```CMake``` for the whole library will be a great addition. I'll see what I can do.

**Comment by JustWhit3** [comment]
Sounds awesome! Unfortunately I am not so familiar with `CMake` at the moment, so it would be a good idea if you could help me with this task.

**Comment by JustWhit3** [comment]
Hi @joeletho ,

Thank you very much, it seems awesome! I am starting learning CMake and many stuff seem clear to me. However, just some reminders before sending a pull request:

- Please, remember to update also all kind of tests in the `test` directory, within all the `.sh` scripts which rely on a compilation part (ex: `all_tests.sh`).
- Update the `docker-compose.yml` file for compiler versions testing and the github actions which have a compilation part into them, i.e `codeql-analysis.yml` and `test-compiler-versions.yml`. It is basically a replacement of all `make` commands with `CMake` ones.
- If possible, run tests on Windows and MacOS also. Codeql analysis workflow already do the job for MacOS. A Windows part should be implemented into it, if possible and should be really quick (just few lines of code), but if you have no time I can do it on my own, not a problem.
- Update the doc and in particular the main `README.md` file with improved building process. I think that parts that need an update are the ones related to installation and usage, i.e `Install and use` section.
- If possible, insert an `installation` and `uninstallation` (don't know if this latter makes sense) command into the CMakeLists.txt file, so one is able to install the library directly after compiling, without the needing of using the scripts into the `scripts` directory.

Thank you very much again for the great work! Really appreciated!!

**Comment by joeletho** [comment]
Hi @JustWhit3,

I'm glad you approve! I will heed your guidelines and continue working on the build system before sending a pull request. When the time comes, is this something you would want pulled directly into main?

**Comment by JustWhit3** [comment]
If all the tests will pass and backward compatibility will not be broken anyway, yes of course!

**Comment by joeletho** [comment]
Great! I'll update you with any issues or concerns as I progress.

**Comment by JustWhit3** [comment]
Hi @joeletho just wanted to let you know that I am working on the CMake building on my own, since I want to follow some specific conventions. I have almost finished the work. When I'll push it fell free to update it or review it if needed.

**Comment by joeletho** [comment]
Hi @JustWhit3, 

Thank you for letting me know. I apologize for not being active as of late. I've been preoccupied with school. I'm looking forward to seeing your changes! Let me know if I can be of any help, or if there's another task you would like me to see to. 

Best,
Joel

**Comment by JustWhit3** [comment]
Don't worry, it is open-source so one should be able to work on it whenever he/she wants! I will update my todo list soon and let you know what are the next steps to be done on the library development ok? Have a nice weekend.

**Comment by JustWhit3** [comment]
CMake building process finally set-up.
