### ISSUE TITLE
Add port to Vcpkg

### ISSUE THREAD

**Issue by Toxe** [JustWhit3/osmanip#29]
It would be of great benefit to have this available via Vcpkg.

**Comment by Toxe** [comment]
Let me know if there is some progress, maybe I can help with doing some test runs on my systems.

**Comment by JustWhit3** [comment]
Hi @Toxe ,

Sorry for the late update (I was very busy in the previous weeks). Just wanted to let you know that I sent a [PR](https://github.com/microsoft/vcpkg/pull/29751) to `vcpkg` repository to add `osmanip` port. Hope they will let me know very soon. I will update you when all the procedure will be completed.

Cheers,
Gianluca.

**Comment by Toxe** [comment]
@JustWhit3 Neat, I'll give it a try once that PR got accepted.

**Comment by JustWhit3** [comment]
Hello @Toxe ,

Just want to let you know that `osmanip` is finally available on `vcpkg` since my [PR](https://github.com/microsoft/vcpkg/pull/30016#event-8701264500) has been merged into master.

You can now install it with:

```c++
vcpkg install osmanip
```

**Comment by Toxe** [comment]
@JustWhit3 Nice, I'll check it out when I have the time.
