### ISSUE TITLE
Unable to compile examples and tests on MSVC (error got from CodeQL analysis workflow)

### ISSUE THREAD

**Issue by JustWhit3** [JustWhit3/osmanip#30]
Hi @joeletho ,

I set up the CMake building process, but an error occurs when trying to compile with MSVC and it seems it is related to `output_redirector.cpp`. As you can see from running the CodeQL workflow for Windows, this error occurs:

```txt
D:\a\osmanip\osmanip\src\utility\output_redirector.cpp(76,4): error C2512: 'std::basic_ostream<char,std::char_traits<char>>': no appropriate default constructor available [D:\a\osmanip\osmanip\build\osmanip.vcxproj]
```

and subsequently:

```txt
D:\a\osmanip\osmanip\src\utility\output_redirector.cpp(73,13): error C2665: 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string': no overloaded function could convert all the argument types [D:\a\osmanip\osmanip\build\osmanip.vcxproj]
```

Do you have any idea of what's happening? Could you please investigate this issue and try to fix it? Thanks.

**Comment by joeletho** [comment]
Hi @JustWhit3,

I took care of the initial problem, which was easy enough, but compilation still fails. Here are my findings:

1. Upon building, CMake gives the following warnings for both ```arsenalgear``` and ```doctest```:
```
  CMake Warning at deps/doctest/CMakeLists.txt:19 (find_package):
    By not providing "Finddoctest.cmake" in CMAKE_MODULE_PATH this project has
    asked CMake to find a package configuration file provided by "doctest", but
    CMake did not find one.

    Could not find a package configuration file provided by "doctest" with any
    of the following names:

      doctestConfig.cmake
      doctest-config.cmake

    Add the installation prefix of "doctest" to CMAKE_PREFIX_PATH or set
    "doctest_DIR" to a directory containing one of the above files.  If
    "doctest" provides a separate development package or SDK, be sure it has
    been installed.
```
It builds and runs perfectly on WSL, so this seems to be only a MSVC issue.

2.
```
FAILED: examples/osmanip_graphics.exe 
cmd.exe /C "cd . && "C:\Program Files\JetBrains\CLion 2021.3.1\bin\cmake\win\bin\cmake.exe" -E vs_link_exe --intdir=examples\CMakeFiles\osmanip_graphics.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x86\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x86\mt.exe --manifests  -- C:\PROGRA~1\MICROS~2\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx86\x86\link.exe /nologo examples\CMakeFiles\osmanip_graphics.dir\graphics.cpp.obj  /out:examples\osmanip_graphics.exe /implib:examples\osmanip_graphics.lib /pdb:examples\osmanip_graphics.pdb /version:0.0 /machine:X86 /debug /INCREMENTAL /subsystem:console  osmanip.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
LINK Pass 1: command "C:\PROGRA~1\MICROS~2\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx86\x86\link.exe /nologo examples\CMakeFiles\osmanip_graphics.dir\graphics.cpp.obj /out:examples\osmanip_graphics.exe /implib:examples\osmanip_graphics.lib /pdb:examples\osmanip_graphics.pdb /version:0.0 /machine:X86 /debug /INCREMENTAL /subsystem:console osmanip.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:examples\CMakeFiles\osmanip_graphics.dir/intermediate.manifest examples\CMakeFiles\osmanip_graphics.dir/manifest.res" failed (exit code 1120) with the following output:
osmanip.lib(windows.cpp.obj) : error LNK2019: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl agr::getCommandOut(char const *)" (?getCommandOut@agr@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PBD@Z) referenced in function "void __cdecl osm::enableUNICODE(void)" (?enableUNICODE@osm@@YAXXZ)
osmanip.lib(windows.cpp.obj) : error LNK2019: unresolved external symbol "class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > __cdecl agr::split_string(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?split_string@agr@@YA?AV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@0@Z) referenced in function "void __cdecl osm::enableUNICODE(void)" (?enableUNICODE@osm@@YAXXZ)
examples\osmanip_graphics.exe : fatal error LNK1120: 2 unresolved externals
ninja: build stopped: subcommand failed.
```
A linking error with ```agr::getCommandOut()```, which I assume is due to the first issue and probably isn't going to be the only one.

In short, by providing a ```Finddoctest.cmake``` and ```Findarsenalgear.cmake```, the libraries can be found by CMake and correctly linked.

Let me know your thoughts.

Best,
Joel

**Comment by JustWhit3** [comment]
Hi @joeletho , the warning is normal and is due to the fact that I added `find_package` in the `deps` CmakeLists.txt before any package fetching. This is simply to remind the user that a dep is not installed and is required, so I am pretty sure that these warnings are not the problem. However it seems that now the problem is unrelated to `output_redirector` right?

**Comment by joeletho** [comment]
Hi @joeletho,
I thought so too, but even after reinstalling ```arsenalgear``` the problem still occurred. Could it be a pathing to the install directory? It will be different on Windows than on Linux.

And yes, ```output_redirector``` has been corrected.

**Comment by JustWhit3** [comment]
Thank you very much. I will try to investigate it in the next days to see what is going on, since I have no idea of what is happening.

I will also update the todo list in case you want to pick uo another topic and develope it!

Have a nice weekend!

**Comment by joeletho** [comment]
Absolutely! And please let me know if you need me to look into anything Windows that you need looking in to. Always happy to help!

Enjoy your weekend as well!

**Comment by JustWhit3** [comment]
However a very first thing that you could do to help me is to investigate what is going on with this `arsenalgear` error. Maybe you can try to build `arsenalgear` (see the repo) with MSVC and check if there are no errors. In this latter case, you could try to investigate the error related to `osmanip`. You could be of a great help for me since I am not familiar with MSVC at all.

Of course I would feature you into the `arsenalgear` contributor list too, that's obvious.

Let me know if you can do it!

**Comment by joeletho** [comment]
Hi @JustWhit3, 

I will do some investigating and see what I can find. It may be a few days, but I will let know what I find.

**Comment by JustWhit3** [comment]
Awesome! Thank you very much.

**Comment by JustWhit3** [comment]
Hi @joeletho , 

I updated the todo list in the main README so, once the MSVC error will be fixed, you will be free (if you want) to keep a todo item and develope it! In case you will choose one of them let me know, thanks.

**Comment by joeletho** [comment]
Hi @JustWhit3, 

I hope you had a good holiday! 

I have put some hours into this issue and I can't seem to figure out what is going on. ```doctest``` is giving me the most grief. However, I feel like the underlying issue is the real problem. Here is the log output:

```
-- The CXX compiler identification is MSVC 19.33.31630.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx86/x86/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at deps/doctest/CMakeLists.txt:19 (find_package):
  By not providing "Finddoctest.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "doctest", but
  CMake did not find one.

  Could not find a package configuration file provided by "doctest" with any
  of the following names:

    doctestConfig.cmake
    doctest-config.cmake

  Add the installation prefix of "doctest" to CMAKE_PREFIX_PATH or set
  "doctest_DIR" to a directory containing one of the above files.  If
  "doctest" provides a separate development package or SDK, be sure it has
  been installed.


-- Fetching doctest...
CMake Error: The current CMakeCache.txt directory C:/Users/Joel/Dev/cpp/osmanip_repos/osmanip_issue30/cmake-build-debug/_deps/doctest-subbuild/CMakeCache.txt is different than the directory c:/Users/Joel/Dev/osmanip_repos/osmanip_issue30/cmake-build-debug/_deps/doctest-subbuild where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt

CMake Error at C:/Program Files/JetBrains/CLion 2021.3.1/bin/cmake/win/share/cmake-3.23/Modules/FetchContent.cmake:1076 (message):
  CMake step for doctest failed: 1

Call Stack (most recent call first):
  C:/Program Files/JetBrains/CLion 2021.3.1/bin/cmake/win/share/cmake-3.23/Modules/FetchContent.cmake:1217:EVAL:2 (__FetchContent_directPopulate)
  C:/Program Files/JetBrains/CLion 2021.3.1/bin/cmake/win/share/cmake-3.23/Modules/FetchContent.cmake:1217 (cmake_language)
  C:/Program Files/JetBrains/CLion 2021.3.1/bin/cmake/win/share/cmake-3.23/Modules/FetchContent.cmake:1260 (FetchContent_Populate)
  deps/doctest/CMakeLists.txt:29 (FetchContent_MakeAvailable)
```
If you read the error after attempting to fetch ```doctest```, CMake seems to be having trouble differentiating between ```doctest```'s CMakeCache and ```osmanip```'s ` CMakeCache. This error is thrown from the following block from ```deps/doctest/CMakeLists.txt```:

```
# Fetch the package
find_package( doctest )

if( NOT doctest_FOUND )
    include(FetchContent)
    FetchContent_Declare(
      doctest
      GIT_REPOSITORY "https://github.com/doctest/doctest"
      GIT_TAG master
    )
    message( STATUS "Fetching doctest..." )
    FetchContent_MakeAvailable( doctest ) # error occurs here
endif()
```
This also happens to ```arsenalgear``` whether it is installed or not. 

So, I think the issue boils down to a problem with the code in the ```CMakeLists.txt``` script or a problem with the pathing. I cannot get any resolve when experimenting with and setting/appending paths, CMake never finds ```arsenalgear``` or ```doctest``` even though both have been fetched and can be found in the ```build/_deps```. Do you have any ideas?

**Comment by JustWhit3** [comment]
Hi @joeletho ,

Thanks, I had good holidaysm hope you too!

This problem is weird. Sincerly I have no idea about how to solve it, because in my devices it perfectly works. Have you tried disabling the `doctest` dep fetching? Does it work in this case? Because if the answer is affermative we can build the library without tests in release mode, and the job is done. Let me know!

PS: for what regard `arsenalgear` it works with `doctest` fetching, in fact all the workflos pass. This is strange too.

**Comment by joeletho** [comment]
Hi @JustWhit3 ,

Yes, it's SO weird. Disabling the ``doctest``` fetching does not fix the issue because the problem then occurs inside ```arsenalgear```'s call to ```doctest``` inside its build tree. Furthermore, if ```doctest``` is removed as a ```arsenalgear``` dependency, then an exception is called when compiling ```osmanip``` because of an ```export doctest``` statement from ```osmanip```. Fetching ```doctest``` in ```arsenalgear``` does work as expected when building ```arsenalgear``` by itself, but fails with ```osmanip```.

It seems to me like there's some confusion with the paths in CMake when running ```cmake .``` on the top-level CMakeLists.txt (```osmanip```) and the CMakeLists.txt of dependencies when they are being built by CMake which happens before ```osmanip```. 

To make it more confusing, when setting paths, like ```arsenalgear_DIR```, as suggested by the CMake error, the path is not set and there is no change. I have only set the paths inside the respective CMakeLists.txt of the dependencies, though maybe I will see different results if I set them in the top-level file. I have avoided this because setting ```arsenalgear_DIR``` and ```doctest_DIR``` in the root CMakeLists.txt isn't very pretty.

**Comment by joeletho** [comment]
@JustWhit3 ,

I just tested it out, disabled the ```doctest``` dependency from ```osmanip``` and set the path in the root CMakeLists.txt and here are my results:
It worked, but with a caveat:
```
======================================================
     BOLD COLORS
======================================================

←[1;30mThis is a bold black string.←[22m ←[39m
←[1;31mThis is a bold red string.←[22m ←[39m
←[1;32mThis is a bold green string.←[22m ←[39m
←[1;33mThis is a bold orange string.←[22m ←[39m
←[1;34mThis is a bold blue string.←[22m ←[39m
←[1;35mThis is a bold purple string.←[22m ←[39m
←[1;36mThis is a bold cyan string.←[22m ←[39m
←[1;37mThis is a bold gray string.←[22m ←[39m

===============←[31m←[1mThe stderr stream has been changed using the OS_Decorator class!←[0m
←[94m←[3m←[4mThe stdlog stream has been changed using the OS_Decorator class!←[0m
```
The formatting is messed up and I'm not sure why yet. My theory is it has something to do with escape sequences on Windows vs. Linux/Unix where Windows = "\n\r" and Linux = "\n". However, the example for ```output_redirector``` works as expected, except for a random ```←[?25h←[0m``` on the very last line. 

Now that I have this I'll do some more investigating.

**Comment by JustWhit3** [comment]
Mmm, maybe this is related to the fact that on Windows ANSI escape sequences are disabled by default? Or maybe the right answer is your. Let me know what you will understand about it!

**Comment by joeletho** [comment]
I didn't even consider that, but that very well may be related. Considering the output still has the escape sequences, it does seems to be disabled. Why are ANSI escape sequences disabled by default on Windows?

**Comment by JustWhit3** [comment]
I don't know exactly the reason, but it is by default. The strange thing is that in the examples I enable them when OS is Windows, so don't understand why it is not working.

**Comment by joeletho** [comment]
Ok. That at least gives me some information so I have something to look into.

**Comment by JustWhit3** [comment]
Hi @joeletho, any updates about this issue?

**Comment by joeletho** [comment]
Hi @JustWhit3,

None so far. I can't seem to make any progress on this issue and I'm basically out of ideas at this point. My hypothesis is that there is a pathing discrepancy to ```arsenalgear``` and ```doctest```, but I just can't figure it out.

**Comment by JustWhit3** [comment]
@joeletho maybe I found a solution. Will let you know very soon.

**Comment by JustWhit3** [comment]
Bug finally fixed, see last commit https://github.com/JustWhit3/osmanip/commit/73e9136c912c8e42fcc8a0f260adbeb7dd7c40d4 and previous ones. The problem was due to have set wrong Windows utility paths in unit tests and wrong `arsenalgear` library linking (it was linked in examples, but it should have been directly linked in the osmanip library creation, in the base `CMakeLists.txt` file).
